[ 2022-04-28T11:15:59     INFO ] logging to applications insights
[ 2022-04-28T11:16:00     INFO ] [ exists                   ] True
[ 2022-04-28T11:16:01     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS', 'name': 'VMSSReImageRun1SOUTHCENTRALUS', 'type': 'Microsoft.Resources/resourceGroups', 'properties': <azure.mgmt.resource.resources.v2021_04_01.models._models_py3.ResourceGroupProperties object at 0x7f864418c550>, 'location': 'southcentralus', 'managed_by': None, 'tags': None}
[ 2022-04-28T11:16:02     INFO ] [ create                   ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Storage/storageAccounts/vmsspipeline9fc2a6bc', 'name': 'vmsspipeline9fc2a6bc', 'type': 'Microsoft.Storage/storageAccounts', 'tags': {'confidentiality': 'public'}, 'location': 'southcentralus', 'sku': <azure.mgmt.storage.v2021_09_01.models._models_py3.Sku object at 0x7f863e79d430>, 'kind': 'StorageV2', 'identity': None, 'extended_location': None, 'provisioning_state': 'Succeeded', 'primary_endpoints': <azure.mgmt.storage.v2021_09_01.models._models_py3.Endpoints object at 0x7f863e79d250>, 'primary_location': 'southcentralus', 'status_of_primary': 'available', 'last_geo_failover_time': None, 'secondary_location': None, 'status_of_secondary': None, 'creation_time': datetime.datetime(2022, 4, 26, 16, 3, 34, 184382, tzinfo=<isodate.tzinfo.Utc object at 0x7f86464c6610>), 'custom_domain': None, 'sas_policy': None, 'key_policy': None, 'key_creation_time': <azure.mgmt.storage.v2021_09_01.models._models_py3.KeyCreationTime object at 0x7f863e79d100>, 'secondary_endpoints': None, 'encryption': <azure.mgmt.storage.v2021_09_01.models._models_py3.Encryption object at 0x7f863e79d7f0>, 'access_tier': 'Hot', 'azure_files_identity_based_authentication': None, 'enable_https_traffic_only': True, 'network_rule_set': <azure.mgmt.storage.v2021_09_01.models._models_py3.NetworkRuleSet object at 0x7f863e79d3d0>, 'is_sftp_enabled': None, 'is_local_user_enabled': None, 'is_hns_enabled': None, 'geo_replication_stats': None, 'failover_in_progress': None, 'large_file_shares_state': None, 'private_endpoint_connections': [], 'routing_preference': None, 'blob_restore_status': None, 'allow_blob_public_access': True, 'minimum_tls_version': 'TLS1_0', 'allow_shared_key_access': None, 'enable_nfs_v3': None, 'allow_cross_tenant_replication': None, 'default_to_o_auth_authentication': None, 'public_network_access': None, 'immutable_storage_with_versioning': None, 'allowed_copy_scope': None, 'storage_account_sku_conversion_status': None, 'dns_endpoint_type': None}
[ 2022-04-28T11:16:03     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Network/networkSecurityGroups/vmssPeregrineTest-nsg', 'name': 'vmssPeregrineTest-nsg', 'type': 'Microsoft.Network/networkSecurityGroups', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'etag': 'W/"032dcc53-bfb9-4cda-95f8-9d8fe45e7237"', 'security_rules': [<azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f863e0eb370>], 'default_security_rules': [<azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f863e0eb190>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f863e0eb3d0>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f863e0eb400>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f863e0eb430>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f863e0eb460>, <azure.mgmt.network.v2021_05_01.models._models_py3.SecurityRule object at 0x7f863e0eb490>], 'network_interfaces': None, 'subnets': [<azure.mgmt.network.v2021_05_01.models._models_py3.Subnet object at 0x7f863e0eb4f0>], 'flow_logs': None, 'resource_guid': '203bc10e-1f08-45fe-8574-0dda31091c3d', 'provisioning_state': 'Succeeded'}
[ 2022-04-28T11:16:04     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Network/virtualNetworks/vmssPeregrineTest-vnet', 'name': 'vmssPeregrineTest-vnet', 'type': 'Microsoft.Network/virtualNetworks', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'extended_location': None, 'etag': 'W/"afdc11b6-3c43-4b31-b872-581f5fe7295f"', 'address_space': <azure.mgmt.network.v2021_05_01.models._models_py3.AddressSpace object at 0x7f863e0eb640>, 'dhcp_options': None, 'flow_timeout_in_minutes': None, 'subnets': [<azure.mgmt.network.v2021_05_01.models._models_py3.Subnet object at 0x7f863e7957c0>], 'virtual_network_peerings': [], 'resource_guid': 'f9c58b12-e959-47a6-90a3-d01f242a9657', 'provisioning_state': 'Succeeded', 'enable_ddos_protection': False, 'enable_vm_protection': None, 'ddos_protection_plan': None, 'bgp_communities': None, 'encryption': None, 'ip_allocations': None}
[ 2022-04-28T11:16:04     INFO ] [ subnets_list             ] <iterator object azure.core.paging.ItemPaged at 0x7f863e795940>
[ 2022-04-28T11:16:05     INFO ] [ get                      ] {'additional_properties': {}, 'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachineScaleSets/vmssPeregrineTest', 'name': 'vmssPeregrineTest', 'type': 'Microsoft.Compute/virtualMachineScaleSets', 'location': 'southcentralus', 'tags': {'confidentiality': 'public'}, 'sku': <azure.mgmt.compute.v2021_11_01.models._models_py3.Sku object at 0x7f863de4df40>, 'plan': None, 'identity': None, 'zones': ['1'], 'extended_location': None, 'upgrade_policy': None, 'automatic_repairs_policy': None, 'virtual_machine_profile': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineScaleSetVMProfile object at 0x7f863de5e490>, 'provisioning_state': 'Succeeded', 'overprovision': None, 'do_not_run_extensions_on_overprovisioned_v_ms': None, 'unique_id': '8348e0b6-fe44-4f7e-81b3-a0dbaa7dfc36', 'single_placement_group': False, 'zone_balance': None, 'platform_fault_domain_count': 1, 'proximity_placement_group': None, 'host_group': None, 'additional_capabilities': None, 'scale_in_policy': None, 'orchestration_mode': 'Flexible', 'spot_restore_policy': None, 'time_created': datetime.datetime(2022, 4, 26, 16, 26, 1, 84949, tzinfo=<FixedOffset '+00:00'>)}
[ 2022-04-28T11:16:05     INFO ] [ get_vms                  ] <iterator object azure.core.paging.ItemPaged at 0x7f863e1176a0>
[ 2022-04-28T11:16:05    DEBUG ] Using selector: EpollSelector
[ 2022-04-28T11:16:05     INFO ] [ get_vms                  ] <iterator object azure.core.paging.ItemPaged at 0x7f863dde3130>
[ 2022-04-28T11:16:06     INFO ] Finish queuing all vms
[ 2022-04-28T11:16:06     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance0H1VQ8', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863de113d0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863de115b0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863de11460>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863de11700>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863de11730>], 'patch_status': None}
[ 2022-04-28T11:16:07     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance0RB9YO', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863d00d790>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863d00d970>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863d00d820>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863d00dac0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863d00daf0>], 'patch_status': None}
[ 2022-04-28T11:16:08     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance3SYUES', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863d017b80>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863d017d60>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863d017c10>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863d017eb0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863d017ee0>], 'patch_status': None}
[ 2022-04-28T11:16:08     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance457RRD', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863d026130>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863d026310>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863d0260d0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863d026490>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863d0264c0>], 'patch_status': None}
[ 2022-04-28T11:16:09     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance53CLNL', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863d032f10>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863c7c1130>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863d032fa0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7c1280>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7c12b0>], 'patch_status': None}
[ 2022-04-28T11:16:09     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance5D58EP', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863d032730>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863d032070>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863d0326d0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863d0324f0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863d032550>], 'patch_status': None}
[ 2022-04-28T11:16:10     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance5K9YCQ', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863c7c5fd0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863c7cb250>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863c7cb100>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7cb3a0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7cb3d0>], 'patch_status': None}
[ 2022-04-28T11:16:10     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstance7JHJ5B', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863c7d1340>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863c7d1520>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863c7d13d0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7d1670>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7d16a0>], 'patch_status': None}
[ 2022-04-28T11:16:11     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstanceAA7RWS', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863c7d58b0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863c7d5a90>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863c7d5940>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7d5be0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7d5c10>], 'patch_status': None}
[ 2022-04-28T11:16:12     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstanceB9R1NT', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863c7dce20>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863c7dcfd0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863c7dceb0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7e5190>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7e51c0>], 'patch_status': None}
[ 2022-04-28T11:16:12  WARNING ] AzureCliCredential.get_token failed: Unexpected output from Azure CLI: '--- Logging error ---
Traceback (most recent call last):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/usr/lib/python3.8/logging/handlers.py", line 171, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib/python3.8/logging/handlers.py", line 111, in rotate
    os.rename(source, dest)
FileNotFoundError: [Errno 2] No such file or directory: '/home/crodriguezde/.azure/telemetry/cache' -> '/home/crodriguezde/.azure/telemetry/cache.1'
Call stack:
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 123, in <module>
    telemetry.conclude()
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 241, in _wrapper
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 297, in conclude
    save(get_config_dir(), _session.generate_payload())
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py", line 51, in save
    if save_payload(config_dir, payload) and should_upload(config_dir):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/util.py", line 53, in save_payload
    cache_saver.info(payload)
Message: '{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"945d58a8-f791-454e-8556-075c446e2b18","Reserved.SequenceNumber":1,"Reserved.SessionId":"34d14f5a966047d4411b1078f458312e70e616e6c8e76cdf67b5217a37162b85","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"account-getaccesstoken","Reserved.DataModel.CorrelationId":"ed8d06a5-4174-4055-85a3-8bf79bab6477","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.35.0@none","Context.Default.VS.Core.MacAddressHash":"e9bfd1348393ff8f258c5b795e82bf541f4459c5b4d6fa911e34d480ac33d348","Context.Default.VS.Core.Machine.Id":"e9bfd134-8393-ff8f-258c-5b795e82bf54","Context.Default.VS.Core.OS.Type":"linux","Context.Default.VS.Core.OS.Version":"#1 smp wed mar 2 00:30:59 utc 2022","Context.Default.VS.Core.OS.Platform":"linux-5.10.102.1-microsoft-standard-wsl2-x86_64-with-glibc2.29","Context.Default.VS.Core.User.Id":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.35.0","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"82910d02-c70e-11ec-a809-00155d785913","Context.Default.AzureCLI.CoreVersion":"2.35.0","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.AzureCLI.ShellType":"/usr/bin/zsh","Context.Default.AzureCLI.UserAzureId":"39921e2f44771b3d76a90cf4cac837fdf8e646729bbbcbe017a174f2298b5c4c","Context.Default.AzureCLI.UserAzureSubscriptionId":"b698965a-1f53-45ec-8b81-58458d1b25f7","Context.Default.AzureCLI.DefaultOutputType":"unknown","Context.Default.AzureCLI.EnvironmentVariables":"[]","Context.Default.AzureCLI.Locale":"en_US,UTF-8","Context.Default.AzureCLI.StartTime":"2022-04-28 16:16:07.554109","Context.Default.AzureCLI.EndTime":"2022-04-28 16:16:07.696628","Context.Default.AzureCLI.InitTimeElapsed":"0.098664","Context.Default.AzureCLI.InvokeTimeElapsed":"0.139991","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"account get-access-token","Context.Default.AzureCLI.Params":"--output,--resource","Context.Default.AzureCLI.PythonVersion":"3.8.10","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"PIP","Context.Default.AzureCLI.error_type":"None","Context.Default.AzureCLI.exception_name":"None","Context.Default.AzureCLI.debug_info":"","Context.Default.AzureCLI.PollStartTime":"None","Context.Default.AzureCLI.PollEndTime":"None"}}]}'
Arguments: ()
{
  ****,
  "expiresOn": "2022-04-28 12:08:35.000000",
  "subscription": "b698965a-1f53-45ec-8b81-58458d1b25f7",
  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "tokenType": "Bearer"
}
'. 
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/azclicredential/troubleshoot.
[ 2022-04-28T11:16:12    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-28T11:16:12    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-28T11:16:12    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-28T11:16:12    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-28T11:16:12    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-28T11:16:12    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-28T11:16:12    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-28T11:16:12    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-28T11:16:12    DEBUG ] Encoding detection on empty bytes, assuming utf_8 intention.
[ 2022-04-28T11:16:36     INFO ] VMs in queue:90
[ 2022-04-28T11:16:42     INFO ] {'compute': {'azEnvironment': 'AzurePublicCloud', 'customData': '', 'evictionPolicy': '', 'extendedLocation': {'name': '', 'type': ''}, 'isHostCompatibilityLayerVm': 'false', 'licenseType': '', 'location': 'southcentralus', 'name': 'vmssPeregrineTest_13561ad1', 'offer': 'UbuntuServer', 'osProfile': {'adminUsername': 'azureUser', 'computerName': 'vmInstance5D58EP', 'disablePasswordAuthentication': 'true'}, 'osType': 'Linux', 'placementGroupId': '', 'plan': {'name': '', 'product': '', 'publisher': ''}, 'platformFaultDomain': '0', 'platformSubFaultDomain': '0', 'platformUpdateDomain': '0', 'priority': '', 'provider': 'Microsoft.Compute', 'publicKeys': [{'keyData': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCq+96OV61LW/TU8BpJ67CvJ00rFktlAUd2uo94eABeKg4+52HKvrdGcbaEUFn2KnyMIKRbHShLvcCtGnOgNJpzClxI3PDPNWEP81jyNs1Tn9ay081mLpDvht5gdlSuHNUB78u2heGK07RvuYhoF4masYcKXdwjSg/Td+san6xDoSvVtST3YFjb3pnb7+DGgzeLqmPBBpr0fw5lmAjtqncrWcb7tbv2T9Ir8Qfc0NMNlDxdC4W54Jk1+FBXJUVAcaDuXqVUX6tLlihfsBubppwN9nxSJahoAaV8HXFUUHjoQEvlN/deAQvTOW8mLv1BZh3tNpMnQYWMt7qL9tSEe30nps+IV/ORRzGg9D4J/kIEnkxoWGe3fgloHaTzHoFwD262wfDIc2fWzlW3/jHLsSG+k7B3+T+mIVxXcsZthjAq57CmH5jHtZv0mmSBdZ9UpJjBcZ1qEhUtNo6pNlcSEJBLzn7wUU3+vRZ6qnQsytQXCA4Bn1/OPjdsPRjakn4c6h6L1qm/PXPlGKiID7uXCo9ZUyiXixTfu5rNgd+Tcsv3pqflUmAsKvJQMvhWeix/EttElOdKWoYcwmDv/Weo9wMFoMzArgP8VZxRIOa6CjK35EHTNINyP8Tz7fjHbnGJIDFiR2k/7n0QwXfSZ000cDI70Q4kuXaIXbqitt3k+rcvOQ==', 'path': '/home/azureUser/.ssh/authorized_keys'}], 'publisher': 'Canonical', 'resourceGroupName': 'VMSSReImageRun1SOUTHCENTRALUS', 'resourceId': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachines/vmssPeregrineTest_13561ad1', 'securityProfile': {'secureBootEnabled': 'false', 'virtualTpmEnabled': 'false'}, 'sku': '18.04-LTS', 'storageProfile': {'dataDisks': [], 'imageReference': {'id': '', 'offer': 'UbuntuServer', 'publisher': 'Canonical', 'sku': '18.04-LTS', 'version': 'latest'}, 'osDisk': {'caching': 'None', 'createOption': 'FromImage', 'diffDiskSettings': {'option': ''}, 'diskSizeGB': '30', 'encryptionSettings': {'enabled': 'false'}, 'image': {'uri': ''}, 'managedDisk': {'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/disks/vmssPeregrineTest_13561ad1_OsDisk_1_a9a1d0f619874d35aea0b801132cb0c2', 'storageAccountType': 'Premium_LRS'}, 'name': 'vmssPeregrineTest_13561ad1_OsDisk_1_a9a1d0f619874d35aea0b801132cb0c2', 'osType': 'Linux', 'vhd': {'uri': ''}, 'writeAcceleratorEnabled': 'false'}, 'resourceDisk': {'size': '34816'}}, 'subscriptionId': 'b698965a-1f53-45ec-8b81-58458d1b25f7', 'tags': 'confidentiality:public', 'tagsList': [{'name': 'confidentiality', 'value': 'public'}], 'userData': '', 'version': '18.04.202204190', 'virtualMachineScaleSet': {'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachineScaleSets/vmssPeregrineTest'}, 'vmId': '7de7c40d-82c9-45f2-b4e3-490eeb8fa8ab', 'vmScaleSetName': 'vmssPeregrineTest', 'vmSize': 'Standard_B1ms', 'zone': '1'}, 'network': {'interface': [{'ipv4': {'ipAddress': [{'privateIpAddress': '10.0.0.41', 'publicIpAddress': ''}], 'subnet': [{'address': '10.0.0.0', 'prefix': '24'}]}, 'ipv6': {'ipAddress': []}, 'macAddress': '002248A5B2B2'}]}}
[ 2022-04-28T11:16:43     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstanceBJGRPR', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863c762a30>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863c762c10>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863c762ac0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c762d60>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c762d90>], 'patch_status': None}
[ 2022-04-28T11:16:43     INFO ] {'compute': {'azEnvironment': 'AzurePublicCloud', 'customData': '', 'evictionPolicy': '', 'extendedLocation': {'name': '', 'type': ''}, 'isHostCompatibilityLayerVm': 'false', 'licenseType': '', 'location': 'southcentralus', 'name': 'vmssPeregrineTest_1b2dea2f', 'offer': 'UbuntuServer', 'osProfile': {'adminUsername': 'azureUser', 'computerName': 'vmInstance7JHJ5B', 'disablePasswordAuthentication': 'true'}, 'osType': 'Linux', 'placementGroupId': '', 'plan': {'name': '', 'product': '', 'publisher': ''}, 'platformFaultDomain': '0', 'platformSubFaultDomain': '5', 'platformUpdateDomain': '0', 'priority': '', 'provider': 'Microsoft.Compute', 'publicKeys': [{'keyData': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCq+96OV61LW/TU8BpJ67CvJ00rFktlAUd2uo94eABeKg4+52HKvrdGcbaEUFn2KnyMIKRbHShLvcCtGnOgNJpzClxI3PDPNWEP81jyNs1Tn9ay081mLpDvht5gdlSuHNUB78u2heGK07RvuYhoF4masYcKXdwjSg/Td+san6xDoSvVtST3YFjb3pnb7+DGgzeLqmPBBpr0fw5lmAjtqncrWcb7tbv2T9Ir8Qfc0NMNlDxdC4W54Jk1+FBXJUVAcaDuXqVUX6tLlihfsBubppwN9nxSJahoAaV8HXFUUHjoQEvlN/deAQvTOW8mLv1BZh3tNpMnQYWMt7qL9tSEe30nps+IV/ORRzGg9D4J/kIEnkxoWGe3fgloHaTzHoFwD262wfDIc2fWzlW3/jHLsSG+k7B3+T+mIVxXcsZthjAq57CmH5jHtZv0mmSBdZ9UpJjBcZ1qEhUtNo6pNlcSEJBLzn7wUU3+vRZ6qnQsytQXCA4Bn1/OPjdsPRjakn4c6h6L1qm/PXPlGKiID7uXCo9ZUyiXixTfu5rNgd+Tcsv3pqflUmAsKvJQMvhWeix/EttElOdKWoYcwmDv/Weo9wMFoMzArgP8VZxRIOa6CjK35EHTNINyP8Tz7fjHbnGJIDFiR2k/7n0QwXfSZ000cDI70Q4kuXaIXbqitt3k+rcvOQ==', 'path': '/home/azureUser/.ssh/authorized_keys'}], 'publisher': 'Canonical', 'resourceGroupName': 'VMSSReImageRun1SOUTHCENTRALUS', 'resourceId': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachines/vmssPeregrineTest_1b2dea2f', 'securityProfile': {'secureBootEnabled': 'false', 'virtualTpmEnabled': 'false'}, 'sku': '18.04-LTS', 'storageProfile': {'dataDisks': [], 'imageReference': {'id': '', 'offer': 'UbuntuServer', 'publisher': 'Canonical', 'sku': '18.04-LTS', 'version': 'latest'}, 'osDisk': {'caching': 'None', 'createOption': 'FromImage', 'diffDiskSettings': {'option': ''}, 'diskSizeGB': '30', 'encryptionSettings': {'enabled': 'false'}, 'image': {'uri': ''}, 'managedDisk': {'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/disks/vmssPeregrineTest_1b2dea2f_OsDisk_1_b7d125be9e1442888f1aaf6e0d624a00', 'storageAccountType': 'Premium_LRS'}, 'name': 'vmssPeregrineTest_1b2dea2f_OsDisk_1_b7d125be9e1442888f1aaf6e0d624a00', 'osType': 'Linux', 'vhd': {'uri': ''}, 'writeAcceleratorEnabled': 'false'}, 'resourceDisk': {'size': '34816'}}, 'subscriptionId': 'b698965a-1f53-45ec-8b81-58458d1b25f7', 'tags': 'confidentiality:public', 'tagsList': [{'name': 'confidentiality', 'value': 'public'}], 'userData': '', 'version': '18.04.202204190', 'virtualMachineScaleSet': {'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachineScaleSets/vmssPeregrineTest'}, 'vmId': '51f6d30c-233f-48b2-b20d-98502c6939a3', 'vmScaleSetName': 'vmssPeregrineTest', 'vmSize': 'Standard_B1ms', 'zone': '1'}, 'network': {'interface': [{'ipv4': {'ipAddress': [{'privateIpAddress': '10.0.0.35', 'publicIpAddress': ''}], 'subnet': [{'address': '10.0.0.0', 'prefix': '24'}]}, 'ipv6': {'ipAddress': []}, 'macAddress': '002248A5B330'}]}}
[ 2022-04-28T11:16:43     INFO ] {'compute': {'azEnvironment': 'AzurePublicCloud', 'customData': '', 'evictionPolicy': '', 'extendedLocation': {'name': '', 'type': ''}, 'isHostCompatibilityLayerVm': 'false', 'licenseType': '', 'location': 'southcentralus', 'name': 'vmssPeregrineTest_01b507e0', 'offer': 'UbuntuServer', 'osProfile': {'adminUsername': 'azureUser', 'computerName': 'vmInstance0H1VQ8', 'disablePasswordAuthentication': 'true'}, 'osType': 'Linux', 'placementGroupId': '', 'plan': {'name': '', 'product': '', 'publisher': ''}, 'platformFaultDomain': '0', 'platformSubFaultDomain': '7', 'platformUpdateDomain': '0', 'priority': '', 'provider': 'Microsoft.Compute', 'publicKeys': [{'keyData': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCq+96OV61LW/TU8BpJ67CvJ00rFktlAUd2uo94eABeKg4+52HKvrdGcbaEUFn2KnyMIKRbHShLvcCtGnOgNJpzClxI3PDPNWEP81jyNs1Tn9ay081mLpDvht5gdlSuHNUB78u2heGK07RvuYhoF4masYcKXdwjSg/Td+san6xDoSvVtST3YFjb3pnb7+DGgzeLqmPBBpr0fw5lmAjtqncrWcb7tbv2T9Ir8Qfc0NMNlDxdC4W54Jk1+FBXJUVAcaDuXqVUX6tLlihfsBubppwN9nxSJahoAaV8HXFUUHjoQEvlN/deAQvTOW8mLv1BZh3tNpMnQYWMt7qL9tSEe30nps+IV/ORRzGg9D4J/kIEnkxoWGe3fgloHaTzHoFwD262wfDIc2fWzlW3/jHLsSG+k7B3+T+mIVxXcsZthjAq57CmH5jHtZv0mmSBdZ9UpJjBcZ1qEhUtNo6pNlcSEJBLzn7wUU3+vRZ6qnQsytQXCA4Bn1/OPjdsPRjakn4c6h6L1qm/PXPlGKiID7uXCo9ZUyiXixTfu5rNgd+Tcsv3pqflUmAsKvJQMvhWeix/EttElOdKWoYcwmDv/Weo9wMFoMzArgP8VZxRIOa6CjK35EHTNINyP8Tz7fjHbnGJIDFiR2k/7n0QwXfSZ000cDI70Q4kuXaIXbqitt3k+rcvOQ==', 'path': '/home/azureUser/.ssh/authorized_keys'}], 'publisher': 'Canonical', 'resourceGroupName': 'VMSSReImageRun1SOUTHCENTRALUS', 'resourceId': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachines/vmssPeregrineTest_01b507e0', 'securityProfile': {'secureBootEnabled': 'false', 'virtualTpmEnabled': 'false'}, 'sku': '18.04-LTS', 'storageProfile': {'dataDisks': [], 'imageReference': {'id': '', 'offer': 'UbuntuServer', 'publisher': 'Canonical', 'sku': '18.04-LTS', 'version': 'latest'}, 'osDisk': {'caching': 'None', 'createOption': 'FromImage', 'diffDiskSettings': {'option': ''}, 'diskSizeGB': '30', 'encryptionSettings': {'enabled': 'false'}, 'image': {'uri': ''}, 'managedDisk': {'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/disks/vmssPeregrineTest_01b507e0_OsDisk_1_fd99c3451ac648f0831ab240ed2bacba', 'storageAccountType': 'Premium_LRS'}, 'name': 'vmssPeregrineTest_01b507e0_OsDisk_1_fd99c3451ac648f0831ab240ed2bacba', 'osType': 'Linux', 'vhd': {'uri': ''}, 'writeAcceleratorEnabled': 'false'}, 'resourceDisk': {'size': '34816'}}, 'subscriptionId': 'b698965a-1f53-45ec-8b81-58458d1b25f7', 'tags': 'confidentiality:public', 'tagsList': [{'name': 'confidentiality', 'value': 'public'}], 'userData': '', 'version': '18.04.202204190', 'virtualMachineScaleSet': {'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachineScaleSets/vmssPeregrineTest'}, 'vmId': 'd9a4abdd-5733-47d9-8992-0cd73bd33069', 'vmScaleSetName': 'vmssPeregrineTest', 'vmSize': 'Standard_B1ms', 'zone': '1'}, 'network': {'interface': [{'ipv4': {'ipAddress': [{'privateIpAddress': '10.0.0.66', 'publicIpAddress': ''}], 'subnet': [{'address': '10.0.0.0', 'prefix': '24'}]}, 'ipv6': {'ipAddress': []}, 'macAddress': '002248A5B082'}]}}
[ 2022-04-28T11:16:43     INFO ] {'compute': {'azEnvironment': 'AzurePublicCloud', 'customData': '', 'evictionPolicy': '', 'extendedLocation': {'name': '', 'type': ''}, 'isHostCompatibilityLayerVm': 'false', 'licenseType': '', 'location': 'southcentralus', 'name': 'vmssPeregrineTest_140cde2a', 'offer': 'UbuntuServer', 'osProfile': {'adminUsername': 'azureUser', 'computerName': 'vmInstance5K9YCQ', 'disablePasswordAuthentication': 'true'}, 'osType': 'Linux', 'placementGroupId': '', 'plan': {'name': '', 'product': '', 'publisher': ''}, 'platformFaultDomain': '0', 'platformSubFaultDomain': '8', 'platformUpdateDomain': '0', 'priority': '', 'provider': 'Microsoft.Compute', 'publicKeys': [{'keyData': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCq+96OV61LW/TU8BpJ67CvJ00rFktlAUd2uo94eABeKg4+52HKvrdGcbaEUFn2KnyMIKRbHShLvcCtGnOgNJpzClxI3PDPNWEP81jyNs1Tn9ay081mLpDvht5gdlSuHNUB78u2heGK07RvuYhoF4masYcKXdwjSg/Td+san6xDoSvVtST3YFjb3pnb7+DGgzeLqmPBBpr0fw5lmAjtqncrWcb7tbv2T9Ir8Qfc0NMNlDxdC4W54Jk1+FBXJUVAcaDuXqVUX6tLlihfsBubppwN9nxSJahoAaV8HXFUUHjoQEvlN/deAQvTOW8mLv1BZh3tNpMnQYWMt7qL9tSEe30nps+IV/ORRzGg9D4J/kIEnkxoWGe3fgloHaTzHoFwD262wfDIc2fWzlW3/jHLsSG+k7B3+T+mIVxXcsZthjAq57CmH5jHtZv0mmSBdZ9UpJjBcZ1qEhUtNo6pNlcSEJBLzn7wUU3+vRZ6qnQsytQXCA4Bn1/OPjdsPRjakn4c6h6L1qm/PXPlGKiID7uXCo9ZUyiXixTfu5rNgd+Tcsv3pqflUmAsKvJQMvhWeix/EttElOdKWoYcwmDv/Weo9wMFoMzArgP8VZxRIOa6CjK35EHTNINyP8Tz7fjHbnGJIDFiR2k/7n0QwXfSZ000cDI70Q4kuXaIXbqitt3k+rcvOQ==', 'path': '/home/azureUser/.ssh/authorized_keys'}], 'publisher': 'Canonical', 'resourceGroupName': 'VMSSReImageRun1SOUTHCENTRALUS', 'resourceId': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachines/vmssPeregrineTest_140cde2a', 'securityProfile': {'secureBootEnabled': 'false', 'virtualTpmEnabled': 'false'}, 'sku': '18.04-LTS', 'storageProfile': {'dataDisks': [], 'imageReference': {'id': '', 'offer': 'UbuntuServer', 'publisher': 'Canonical', 'sku': '18.04-LTS', 'version': 'latest'}, 'osDisk': {'caching': 'None', 'createOption': 'FromImage', 'diffDiskSettings': {'option': ''}, 'diskSizeGB': '30', 'encryptionSettings': {'enabled': 'false'}, 'image': {'uri': ''}, 'managedDisk': {'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/disks/vmssPeregrineTest_140cde2a_OsDisk_1_53573115adf44fcaae3dbbf1400f0ca7', 'storageAccountType': 'Premium_LRS'}, 'name': 'vmssPeregrineTest_140cde2a_OsDisk_1_53573115adf44fcaae3dbbf1400f0ca7', 'osType': 'Linux', 'vhd': {'uri': ''}, 'writeAcceleratorEnabled': 'false'}, 'resourceDisk': {'size': '34816'}}, 'subscriptionId': 'b698965a-1f53-45ec-8b81-58458d1b25f7', 'tags': 'confidentiality:public', 'tagsList': [{'name': 'confidentiality', 'value': 'public'}], 'userData': '', 'version': '18.04.202204190', 'virtualMachineScaleSet': {'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachineScaleSets/vmssPeregrineTest'}, 'vmId': 'b7420adf-8363-48cd-838d-7c8ecf46cfc7', 'vmScaleSetName': 'vmssPeregrineTest', 'vmSize': 'Standard_B1ms', 'zone': '1'}, 'network': {'interface': [{'ipv4': {'ipAddress': [{'privateIpAddress': '10.0.0.100', 'publicIpAddress': ''}], 'subnet': [{'address': '10.0.0.0', 'prefix': '24'}]}, 'ipv6': {'ipAddress': []}, 'macAddress': '002248A5B9B6'}]}}
[ 2022-04-28T11:16:43     INFO ] {'compute': {'azEnvironment': 'AzurePublicCloud', 'customData': '', 'evictionPolicy': '', 'extendedLocation': {'name': '', 'type': ''}, 'isHostCompatibilityLayerVm': 'false', 'licenseType': '', 'location': 'southcentralus', 'name': 'vmssPeregrineTest_0ef03d49', 'offer': 'UbuntuServer', 'osProfile': {'adminUsername': 'azureUser', 'computerName': 'vmInstance457RRD', 'disablePasswordAuthentication': 'true'}, 'osType': 'Linux', 'placementGroupId': '', 'plan': {'name': '', 'product': '', 'publisher': ''}, 'platformFaultDomain': '0', 'platformSubFaultDomain': '9', 'platformUpdateDomain': '0', 'priority': '', 'provider': 'Microsoft.Compute', 'publicKeys': [{'keyData': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCq+96OV61LW/TU8BpJ67CvJ00rFktlAUd2uo94eABeKg4+52HKvrdGcbaEUFn2KnyMIKRbHShLvcCtGnOgNJpzClxI3PDPNWEP81jyNs1Tn9ay081mLpDvht5gdlSuHNUB78u2heGK07RvuYhoF4masYcKXdwjSg/Td+san6xDoSvVtST3YFjb3pnb7+DGgzeLqmPBBpr0fw5lmAjtqncrWcb7tbv2T9Ir8Qfc0NMNlDxdC4W54Jk1+FBXJUVAcaDuXqVUX6tLlihfsBubppwN9nxSJahoAaV8HXFUUHjoQEvlN/deAQvTOW8mLv1BZh3tNpMnQYWMt7qL9tSEe30nps+IV/ORRzGg9D4J/kIEnkxoWGe3fgloHaTzHoFwD262wfDIc2fWzlW3/jHLsSG+k7B3+T+mIVxXcsZthjAq57CmH5jHtZv0mmSBdZ9UpJjBcZ1qEhUtNo6pNlcSEJBLzn7wUU3+vRZ6qnQsytQXCA4Bn1/OPjdsPRjakn4c6h6L1qm/PXPlGKiID7uXCo9ZUyiXixTfu5rNgd+Tcsv3pqflUmAsKvJQMvhWeix/EttElOdKWoYcwmDv/Weo9wMFoMzArgP8VZxRIOa6CjK35EHTNINyP8Tz7fjHbnGJIDFiR2k/7n0QwXfSZ000cDI70Q4kuXaIXbqitt3k+rcvOQ==', 'path': '/home/azureUser/.ssh/authorized_keys'}], 'publisher': 'Canonical', 'resourceGroupName': 'VMSSReImageRun1SOUTHCENTRALUS', 'resourceId': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachines/vmssPeregrineTest_0ef03d49', 'securityProfile': {'secureBootEnabled': 'false', 'virtualTpmEnabled': 'false'}, 'sku': '18.04-LTS', 'storageProfile': {'dataDisks': [], 'imageReference': {'id': '', 'offer': 'UbuntuServer', 'publisher': 'Canonical', 'sku': '18.04-LTS', 'version': 'latest'}, 'osDisk': {'caching': 'None', 'createOption': 'FromImage', 'diffDiskSettings': {'option': ''}, 'diskSizeGB': '30', 'encryptionSettings': {'enabled': 'false'}, 'image': {'uri': ''}, 'managedDisk': {'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/disks/vmssPeregrineTest_0ef03d49_OsDisk_1_5c70e3f70eff41cfacd8f94e8ff85ac6', 'storageAccountType': 'Premium_LRS'}, 'name': 'vmssPeregrineTest_0ef03d49_OsDisk_1_5c70e3f70eff41cfacd8f94e8ff85ac6', 'osType': 'Linux', 'vhd': {'uri': ''}, 'writeAcceleratorEnabled': 'false'}, 'resourceDisk': {'size': '34816'}}, 'subscriptionId': 'b698965a-1f53-45ec-8b81-58458d1b25f7', 'tags': 'confidentiality:public', 'tagsList': [{'name': 'confidentiality', 'value': 'public'}], 'userData': '', 'version': '18.04.202204190', 'virtualMachineScaleSet': {'id': '/subscriptions/b698965a-1f53-45ec-8b81-58458d1b25f7/resourceGroups/VMSSReImageRun1SOUTHCENTRALUS/providers/Microsoft.Compute/virtualMachineScaleSets/vmssPeregrineTest'}, 'vmId': '8aeba608-ed4e-42c4-9845-05124d856c39', 'vmScaleSetName': 'vmssPeregrineTest', 'vmSize': 'Standard_B1ms', 'zone': '1'}, 'network': {'interface': [{'ipv4': {'ipAddress': [{'privateIpAddress': '10.0.0.87', 'publicIpAddress': ''}], 'subnet': [{'address': '10.0.0.0', 'prefix': '24'}]}, 'ipv6': {'ipAddress': []}, 'macAddress': '002248A5BAE8'}]}}
[ 2022-04-28T11:16:43     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstanceCHWLGH', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863c759fa0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863c759160>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863c759250>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7595e0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c759550>], 'patch_status': None}
[ 2022-04-28T11:16:44     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstanceCIUBDR', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863c7775e0>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863c74ebb0>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863c74ea30>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c7776d0>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c777700>], 'patch_status': None}
[ 2022-04-28T11:16:45     INFO ] [ get                      ] {'additional_properties': {}, 'platform_update_domain': None, 'platform_fault_domain': None, 'computer_name': 'vmInstanceCMAHQN', 'os_name': 'ubuntu', 'os_version': '18.04', 'hyper_v_generation': 'V1', 'rdp_thumb_print': None, 'vm_agent': <azure.mgmt.compute.v2021_11_01.models._models_py3.VirtualMachineAgentInstanceView object at 0x7f863c70a250>, 'maintenance_redeploy_status': None, 'disks': [<azure.mgmt.compute.v2021_11_01.models._models_py3.DiskInstanceView object at 0x7f863c70a430>], 'extensions': [], 'vm_health': None, 'boot_diagnostics': <azure.mgmt.compute.v2021_11_01.models._models_py3.BootDiagnosticsInstanceView object at 0x7f863c70a2e0>, 'assigned_host': None, 'statuses': [<azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c70a580>, <azure.mgmt.compute.v2021_11_01.models._models_py3.InstanceViewStatus object at 0x7f863c70a5b0>], 'patch_status': None}
[ 2022-04-28T11:16:45    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f863d026e80>
[ 2022-04-28T11:16:45    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f863c7d1d60>
[ 2022-04-28T11:16:45    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f863c7dc940>
[ 2022-04-28T11:16:45    ERROR ] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f863c7ec160>
[ 2022-04-28T11:16:45    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-5' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:30> exception=ClientAuthenticationError('Unexpected output from Azure CLI: \'--- Logging error ---\nTraceback (most recent call last):\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 60, in <module>\n    raise ex\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 53, in <module>\n    sys.exit(exit_code)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.8/logging/handlers.py", line 70, in emit\n    self.doRollover()\n  File "/usr/lib/python3.8/logging/handlers.py", line 171, in doRollover\n    self.rotate(self.baseFilename, dfn)\n  File "/usr/lib/python3.8/logging/handlers.py", line 111, in rotate\n    os.rename(source, dest)\nFileNotFoundError: [Errno 2] No such file or directory: \'/home/crodriguezde/.azure/telemetry/cache\' -> \'/home/crodriguezde/.azure/telemetry/cache.1\'\nCall stack:\n  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 123, in <module>\n    telemetry.conclude()\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 241, in _wrapper\n    return func(*args, **kwargs)\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func\n    return func(*args, **kwargs)\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 297, in conclude\n    save(get_config_dir(), _session.generate_payload())\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py", line 51, in save\n    if save_payload(config_dir, payload) and should_upload(config_dir):\n  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/util.py", line 53, in save_payload\n    cache_saver.info(payload)\nMessage: \'{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"945d58a8-f791-454e-8556-075c446e2b18","Reserved.SequenceNumber":1,"Reserved.SessionId":"34d14f5a966047d4411b1078f458312e70e616e6c8e76cdf67b5217a37162b85","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"account-getaccesstoken","Reserved.DataModel.CorrelationId":"ed8d06a5-4174-4055-85a3-8bf79bab6477","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.35.0@none","Context.Default.VS.Core.MacAddressHash":"e9bfd1348393ff8f258c5b795e82bf541f4459c5b4d6fa911e34d480ac33d348","Context.Default.VS.Core.Machine.Id":"e9bfd134-8393-ff8f-258c-5b795e82bf54","Context.Default.VS.Core.OS.Type":"linux","Context.Default.VS.Core.OS.Version":"#1 smp wed mar 2 00:30:59 utc 2022","Context.Default.VS.Core.OS.Platform":"linux-5.10.102.1-microsoft-standard-wsl2-x86_64-with-glibc2.29","Context.Default.VS.Core.User.Id":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.35.0","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"82910d02-c70e-11ec-a809-00155d785913","Context.Default.AzureCLI.CoreVersion":"2.35.0","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.AzureCLI.ShellType":"/usr/bin/zsh","Context.Default.AzureCLI.UserAzureId":"39921e2f44771b3d76a90cf4cac837fdf8e646729bbbcbe017a174f2298b5c4c","Context.Default.AzureCLI.UserAzureSubscriptionId":"b698965a-1f53-45ec-8b81-58458d1b25f7","Context.Default.AzureCLI.DefaultOutputType":"unknown","Context.Default.AzureCLI.EnvironmentVariables":"[]","Context.Default.AzureCLI.Locale":"en_US,UTF-8","Context.Default.AzureCLI.StartTime":"2022-04-28 16:16:07.554109","Context.Default.AzureCLI.EndTime":"2022-04-28 16:16:07.696628","Context.Default.AzureCLI.InitTimeElapsed":"0.098664","Context.Default.AzureCLI.InvokeTimeElapsed":"0.139991","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"account get-access-token","Context.Default.AzureCLI.Params":"--output,--resource","Context.Default.AzureCLI.PythonVersion":"3.8.10","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"PIP","Context.Default.AzureCLI.error_type":"None","Context.Default.AzureCLI.exception_name":"None","Context.Default.AzureCLI.debug_info":"","Context.Default.AzureCLI.PollStartTime":"None","Context.Default.AzureCLI.PollEndTime":"None"}}]}\'\nArguments: ()\n{\n  ****,\n  "expiresOn": "2022-04-28 12:08:35.000000",\n  "subscription": "b698965a-1f53-45ec-8b81-58458d1b25f7",\n  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",\n  "tokenType": "Bearer"\n}\n\'. \nTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/azclicredential/troubleshoot.')>
Traceback (most recent call last):
  File "/home/crodriguezde/experiments/reimage/imds.py", line 36, in _get
    instance_vm = _wait_vm_state_running(cli_args, vmss_vm)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/mgmt/compute/v2021_11_01/aio/operations/_virtual_machines_operations.py", line 2289, in begin_run_command
    raw_result = await self._run_command_initial(
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/mgmt/compute/v2021_11_01/aio/operations/_virtual_machines_operations.py", line 2231, in _run_command_initial
    pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 215, in run
    return await first_node.send(pipeline_request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 2 more times]
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/mgmt/core/policies/_base_async.py", line 47, in send
    response = await self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect_async.py", line 64, in send
    response = await self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry_async.py", line 147, in send
    response = await self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication_async.py", line 73, in send
    await await_result(self.on_request, request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_tools_async.py", line 36, in await_result
    return await result  # type: ignore
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication_async.py", line 51, in on_request
    self._token = await self._credential.get_token(*self._scopes)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/identity/aio/_internal/decorators.py", line 21, in wrapper
    token = await fn(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/identity/aio/_credentials/azure_cli.py", line 66, in get_token
    raise ClientAuthenticationError(
azure.core.exceptions.ClientAuthenticationError: Unexpected output from Azure CLI: '--- Logging error ---
Traceback (most recent call last):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/usr/lib/python3.8/logging/handlers.py", line 171, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib/python3.8/logging/handlers.py", line 111, in rotate
    os.rename(source, dest)
FileNotFoundError: [Errno 2] No such file or directory: '/home/crodriguezde/.azure/telemetry/cache' -> '/home/crodriguezde/.azure/telemetry/cache.1'
Call stack:
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/__main__.py", line 123, in <module>
    telemetry.conclude()
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 241, in _wrapper
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func
    return func(*args, **kwargs)
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 297, in conclude
    save(get_config_dir(), _session.generate_payload())
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py", line 51, in save
    if save_payload(config_dir, payload) and should_upload(config_dir):
  File "/home/crodriguezde/.local/lib/python3.8/site-packages/azure/cli/telemetry/util.py", line 53, in save_payload
    cache_saver.info(payload)
Message: '{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"945d58a8-f791-454e-8556-075c446e2b18","Reserved.SequenceNumber":1,"Reserved.SessionId":"34d14f5a966047d4411b1078f458312e70e616e6c8e76cdf67b5217a37162b85","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"account-getaccesstoken","Reserved.DataModel.CorrelationId":"ed8d06a5-4174-4055-85a3-8bf79bab6477","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.35.0@none","Context.Default.VS.Core.MacAddressHash":"e9bfd1348393ff8f258c5b795e82bf541f4459c5b4d6fa911e34d480ac33d348","Context.Default.VS.Core.Machine.Id":"e9bfd134-8393-ff8f-258c-5b795e82bf54","Context.Default.VS.Core.OS.Type":"linux","Context.Default.VS.Core.OS.Version":"#1 smp wed mar 2 00:30:59 utc 2022","Context.Default.VS.Core.OS.Platform":"linux-5.10.102.1-microsoft-standard-wsl2-x86_64-with-glibc2.29","Context.Default.VS.Core.User.Id":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.35.0","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"82910d02-c70e-11ec-a809-00155d785913","Context.Default.AzureCLI.CoreVersion":"2.35.0","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"64c5b0af-e344-11eb-b316-c03c59895c0a","Context.Default.AzureCLI.ShellType":"/usr/bin/zsh","Context.Default.AzureCLI.UserAzureId":"39921e2f44771b3d76a90cf4cac837fdf8e646729bbbcbe017a174f2298b5c4c","Context.Default.AzureCLI.UserAzureSubscriptionId":"b698965a-1f53-45ec-8b81-58458d1b25f7","Context.Default.AzureCLI.DefaultOutputType":"unknown","Context.Default.AzureCLI.EnvironmentVariables":"[]","Context.Default.AzureCLI.Locale":"en_US,UTF-8","Context.Default.AzureCLI.StartTime":"2022-04-28 16:16:07.554109","Context.Default.AzureCLI.EndTime":"2022-04-28 16:16:07.696628","Context.Default.AzureCLI.InitTimeElapsed":"0.098664","Context.Default.AzureCLI.InvokeTimeElapsed":"0.139991","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"account get-access-token","Context.Default.AzureCLI.Params":"--output,--resource","Context.Default.AzureCLI.PythonVersion":"3.8.10","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"PIP","Context.Default.AzureCLI.error_type":"None","Context.Default.AzureCLI.exception_name":"None","Context.Default.AzureCLI.debug_info":"","Context.Default.AzureCLI.PollStartTime":"None","Context.Default.AzureCLI.PollEndTime":"None"}}]}'
Arguments: ()
{
  ****,
  "expiresOn": "2022-04-28 12:08:35.000000",
  "subscription": "b698965a-1f53-45ec-8b81-58458d1b25f7",
  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "tokenType": "Bearer"
}
'. 
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/azclicredential/troubleshoot.
[ 2022-04-28T11:16:45     INFO ] Exit per user request
[ 2022-04-28T11:16:46    ERROR ] Task exception was never retrieved
future: <Task finished name='Task-7' coro=<_get() done, defined at /home/crodriguezde/experiments/reimage/imds.py:30> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "deployer.py", line 142, in <module>
    main()
  File "deployer.py", line 131, in main
    asyncio.run(imds.get_from_vmss_vms(args))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/crodriguezde/experiments/reimage/imds.py", line 33, in _get
    async def _get(cli_args, queue, log_queue):
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/backoff/_sync.py", line 43, in retry
    ret = target(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/imds.py", line 60, in _wait_vm_state_running
  File "/home/crodriguezde/experiments/reimage/utils.py", line 13, in timer
    result = fn(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/vm.py", line 31, in get
    return resource_client.virtual_machines.instance_view(
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/mgmt/compute/v2021_11_01/operations/_virtual_machines_operations.py", line 1626, in instance_view
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 119, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 327, in send
    response = self.session.request(  # type: ignore
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/crodriguezde/experiments/reimage/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
KeyboardInterrupt
